//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schols.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHLRSHP
    {
        public string FUND_ACCT { get; set; }
        public string SCHLRSHP_NUM { get; set; }
        public string SCHLRSHP_TITLE { get; set; }
        public string SCHLRSHP_PGRM { get; set; }
        public string SCHLRSHP_PRPS { get; set; }
        public string SCHLRSHP_CRTRIA { get; set; }
        public decimal CUR_YR_TOT_ALLOC { get; set; }
        public string SCHLRSHP_STTUS { get; set; }
        public string SCHLR_USER_VARBL1 { get; set; }
        public string SCHLR_USER_VARBL2 { get; set; }
        public string SCHLR_USER_VARBL3 { get; set; }
        public string SCHLR_USER_VARBL4 { get; set; }
        public string SCHLR_USER_VARBL5 { get; set; }
        public string SCHLR_USER_VARBL6 { get; set; }
        public string SCHLR_USER_VARBL7 { get; set; }
        public string SCHLR_USER_VARBL8 { get; set; }
        public string SCHLR_USER_VARBL9 { get; set; }
        public string SCHLR_USER_VARBL10 { get; set; }
        public string SCHLR_USER_VARBL11 { get; set; }
        public string SCHLR_USER_VARBL12 { get; set; }
        public string SCHLR_USER_VARBL13 { get; set; }
        public string SCHLR_USER_VARBL14 { get; set; }
        public string SCHLR_USER_VARBL15 { get; set; }
        public string SCHLR_USER_VARBL16 { get; set; }
        public string SCHLR_USER_VARBL17 { get; set; }
        public string SCHLR_USER_VARBL18 { get; set; }
        public string SCHLR_USER_VARBL19 { get; set; }
        public string SCHLR_USER_VARBL20 { get; set; }
        public string SCHLR_USER_VARBL21 { get; set; }
        public string SCHLR_USER_VARBL22 { get; set; }
        public string SCHLR_USER_VARBL23 { get; set; }
        public string SCHLR_USER_VARBL24 { get; set; }
        public string SCHLR_USER_VARBL25 { get; set; }
        public string SCHLR_USER_VARBL26 { get; set; }
        public string SCHLR_USER_VARBL27 { get; set; }
        public string SCHLR_USER_VARBL28 { get; set; }
        public string SCHLR_USER_VARBL29 { get; set; }
        public string SCHLR_USER_VARBL30 { get; set; }
        public string SCHLR_USER_VARBL31 { get; set; }
        public string SCHLR_USER_VARBL32 { get; set; }
        public Nullable<System.DateTime> USER_VARBL_DATEDB1 { get; set; }
        public Nullable<System.DateTime> USER_VARBL_DATEDB2 { get; set; }
        public System.DateTime UPDT_DATEDB { get; set; }
        public string FNCL_AID_ACCT_CD { get; set; }
        public string FRML_SCHLRSHP_NAME { get; set; }
        public Nullable<long> AUDIT_TRAN_ID { get; set; }
        public string FUNDFUND_ACCT { get; set; }
    
        //public virtual FUND FUND { get; set; }
    }
}
